config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :courts
    resources :reservations
    resources :run_schedules
    resources :runs
    resources :users

    root to: "users#index"
  end

  resources :courts
  # resources :reservations
  resources :runs do
    resources :reservations, shallow: true
  end
  resources :run_templates
  resources :users, only: [:index, :new, :create, :show, :edit, :update]

  get '/sign_up', to: 'users#new'

  root 'welcome#index'
end

app/views/shared/_flash.html.erb
<div class="has-text-centered">
  <% flash.each do |key, message| %>
    <div class="flash-container notification py-2 <%= flash_class(key) %>">
      <span class="is-size-5"><%= message %></span>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand is-align-items-center">
    <%= link_to(root_path, id: "bil-brand-link", class: "navbar-item") do %>
      <span class="is-size-2 is-size-3-mobile">Ball is Life</span>
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Home
      </a>

      <a class="navbar-item">
        Documentation
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to(sign_up_path, class: "button is-primary") do %>
            <strong>Sign up</strong>
          <% end %>
          <a class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>