config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :courts
    resources :reservations
    resources :run_schedules
    resources :runs
    resources :users

    root to: "users#index"
  end

  resources :courts
  # resources :reservations
  resources :runs do
    resources :reservations, shallow: true
  end
  resources :run_templates
  resources :users, only: [:index, :new, :create, :show, :edit, :update]

  get '/sign_up', to: 'users#new'

  root 'welcome#index'
end

app/models/court.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: courts
#
#  id             :bigint           not null, primary key
#  city           :string
#  name           :string           not null
#  state          :string
#  street_address :string
#  zip            :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_courts_on_name  (name) UNIQUE
#
class Court < ApplicationRecord
  has_many :run_templates, dependent: :restrict_with_error
  has_many :runs, dependent: :restrict_with_error

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 50 }
end

app/controllers/admin/courts_controller.rb
module Admin
  class CourtsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/courts_controller.rb
# frozen_string_literal: true

class CourtsController < ApplicationController
  before_action :set_court, only: %i[show edit update destroy]

  # GET /courts or /courts.json
  def index
    @courts = Court.all
  end

  # GET /courts/1 or /courts/1.json
  def show; end

  # GET /courts/new
  def new
    @court = Court.new
  end

  # GET /courts/1/edit
  def edit; end

  # POST /courts or /courts.json
  def create
    @court = Court.new(court_params)

    respond_to do |format|
      if @court.save
        format.html { redirect_to court_url(@court), notice: 'Court was successfully created.' }
        format.json { render :show, status: :created, location: @court }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courts/1 or /courts/1.json
  def update
    respond_to do |format|
      if @court.update(court_params)
        format.html { redirect_to court_url(@court), notice: 'Court was successfully updated.' }
        format.json { render :show, status: :ok, location: @court }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courts/1 or /courts/1.json
  def destroy
    @court.destroy

    respond_to do |format|
      format.html { redirect_to courts_url, notice: 'Court was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_court
    @court = Court.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def court_params
    params.require(:court).permit(:name, :street_address, :city, :state, :zip)
  end
end

app/helpers/courts_helper.rb
# frozen_string_literal: true

module CourtsHelper
end

app/views/courts/_court.html.erb
<div id="<%= dom_id court %>">
  <p>
    <strong>Name:</strong>
    <%= court.name %>
  </p>

  <p>
    <strong>Street address:</strong>
    <%= court.street_address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= court.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= court.state %>
  </p>

  <p>
    <strong>Zip:</strong>
    <%= court.zip %>
  </p>

</div>

app/views/courts/_form.html.erb
<%= form_with(model: court) do |form| %>
  <% if court.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(court.errors.count, "error") %> prohibited this court from being saved:</h2>

      <ul>
        <% court.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :street_address, style: "display: block" %>
    <%= form.text_field :street_address %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :zip, style: "display: block" %>
    <%= form.number_field :zip %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courts/edit.html.erb
<h1>Editing court</h1>

<%= render "form", court: @court %>

<br>

<div>
  <%= link_to "Show this court", @court %> |
  <%= link_to "Back to courts", courts_path %>
</div>

app/views/courts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Courts</h1>

<div id="courts">
  <% @courts.each do |court| %>
    <%= render court %>
    <p>
      <%= link_to "Show this court", court %>
    </p>
  <% end %>
</div>

<%= link_to "New court", new_court_path %>

app/views/courts/new.html.erb
<h1>New court</h1>

<%= render "form", court: @court %>

<br>

<div>
  <%= link_to "Back to courts", courts_path %>
</div>

app/views/courts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @court %>

<div>
  <%= link_to "Edit this court", edit_court_path(@court) %> |
  <%= link_to "Back to courts", courts_path %>

  <%= button_to "Destroy this court", @court, method: :delete %>
</div>