config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :courts
    resources :reservations
    resources :run_schedules
    resources :runs
    resources :users

    root to: "users#index"
  end

  resources :courts
  # resources :reservations
  resources :runs do
    resources :reservations, shallow: true
  end
  resources :run_templates
  resources :users, only: [:index, :new, :create, :show, :edit, :update]

  get '/sign_up', to: 'users#new'

  root 'welcome#index'
end

app/controllers/run_templates_controller.rb
# frozen_string_literal: true

class RunTemplatesController < ApplicationController
  before_action :set_run_template, only: %i[show edit update destroy]

  # GET /run_templates or /run_templates.json
  def index
    @run_templates = RunTemplate.all
  end

  # GET /run_templates/1 or /run_templates/1.json
  def show; end

  # GET /run_templates/new
  def new
    @run_template = RunTemplate.new
  end

  # GET /run_templates/1/edit
  def edit; end

  # POST /run_templates or /run_templates.json
  def create
    @run_template = RunTemplate.new(run_template_params)

    respond_to do |format|
      if @run_template.save
        format.html { redirect_to run_template_url(@run_template), notice: 'Run template was successfully created.' }
        format.json { render :show, status: :created, location: @run_template }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @run_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /run_templates/1 or /run_templates/1.json
  def update
    respond_to do |format|
      if @run_template.update(run_template_params)
        format.html { redirect_to run_template_url(@run_template), notice: 'Run template was successfully updated.' }
        format.json { render :show, status: :ok, location: @run_template }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @run_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /run_templates/1 or /run_templates/1.json
  def destroy
    @run_template.destroy

    respond_to do |format|
      format.html { redirect_to run_templates_url, notice: 'Run template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_run_template
    @run_template = RunTemplate.find(params[:id])
  end

  def run_template_params
    # params.fetch(:run_template, {})
    params.require(:run_template).permit(
      :name,
      :court_id,
      :player_limit,
      :total_price_in_dollars,
      :day_of_week,
      :start_hour,
      :start_minute,
      :end_hour,
      :end_minute
    )
  end
end

app/helpers/run_templates_helper.rb
# frozen_string_literal: true

module RunTemplatesHelper
end

app/views/run_templates/_form.html.erb
<%= form_with(model: run_template) do |form| %>
  <% if run_template.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(run_template.errors.count, "error") %> prohibited this run_template from being saved:</h2>

      <ul>
        <% run_template.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :court, style: "display: block" %>
    <%= form.select :court_id, Court.all, value_method: :id, include_blank: true %>
  </div>

  <div>
    <%= form.label :player_limit, style: "display: block" %>
    <%= form.number_field :player_limit %>
  </div>

  <div>
    <%= form.label :total_price_in_dollars, style: "display: block" %>
    <%= form.number_field :total_price_in_dollars %>
  </div>

  <div>
    <%= form.label :day_of_week, style: "display: block" %>
    <%= form.text_field :day_of_week %>
  </div>

  <div>
    <%= form.label :start_hour, style: "display: block" %>
    <%= form.number_field :start_hour %>
  </div>

  <div>
    <%= form.label :start_minute, style: "display: block" %>
    <%= form.number_field :start_minute %>
  </div>

  <div>
    <%= form.label :end_hour, style: "display: block" %>
    <%= form.number_field :end_hour %>
  </div>

  <div>
    <%= form.label :end_minute, style: "display: block" %>
    <%= form.number_field :end_minute %>
  </div>

  <div>
    <%= form.label :repeat_interval, style: "display: block" %>
    <%= form.text_field :repeat_interval %>
  </div>

  <div>
    <%= form.label :repeat_start_date, style: "display: block" %>
    <%= form.date_field :repeat_start_date %>
  </div>

  <div>
    <%= form.label :repeat_end_date, style: "display: block" %>
    <%= form.date_field :repeat_end_date %>
  </div>

  <div>
    <%= form.label :repeat_interval, style: "display: block" %>
    <%= form.text_field :repeat_interval %>
  </div>

  <div>
    <%= form.label :sign_up_open_day, style: "display: block" %>
    <%= form.text_field :sign_up_open_day %>
  </div>

  <div>
    <%= form.label :sign_up_open_hour, style: "display: block" %>
    <%= form.number_field :sign_up_open_hour %>
  </div>

  <div>
    <%= form.label :sign_up_open_minute, style: "display: block" %>
    <%= form.number_field :sign_up_open_minute %>
  </div>

  <div>
    <%= form.label :late_drop_deadline_day, style: "display: block" %>
    <%= form.text_field :late_drop_deadline_day %>
  </div>

  <div>
    <%= form.label :late_drop_deadline_hour, style: "display: block" %>
    <%= form.number_field :late_drop_deadline_hour %>
  </div>

  <div>
    <%= form.label :late_drop_deadline_minute, style: "display: block" %>
    <%= form.number_field :late_drop_deadline_minute %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/run_templates/_run_template.html.erb
<div id="<%= dom_id run_template %>">
</div>

app/views/run_templates/edit.html.erb
<h1>Editing run template</h1>

<%= render "form", run_template: @run_template %>

<br>

<div>
  <%= link_to "Show this run template", @run_template %> |
  <%= link_to "Back to run templates", run_templates_path %>
</div>

app/views/run_templates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Run templates</h1>

<div id="run_templates">
  <% @run_templates.each do |run_template| %>
    <%= render run_template %>
    <p>
      <%= link_to "Show this run template", run_template %>
    </p>
  <% end %>
</div>

<%= link_to "New run template", new_run_template_path %>

app/views/run_templates/new.html.erb
<h1>New run template</h1>

<%= render "form", run_template: @run_template %>

<br>

<div>
  <%= link_to "Back to run templates", run_templates_path %>
</div>

app/views/run_templates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @run_template %>

<div>
  <%= link_to "Edit this run template", edit_run_template_path(@run_template) %> |
  <%= link_to "Back to run templates", run_templates_path %>

  <%= button_to "Destroy this run template", @run_template, method: :delete %>
</div>